markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
syntax_highlighter: rouge

encoding: utf-8
url: http://into-cps.github.io

collections:
  netmeetings:
    output: true
  workshops:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      
